### ISSUE TITLE
Logs in systems without known coords don't show up

### ISSUE THREAD

**Issue by padthaitofuhot** [DBnR1/EDTB#1]
I noticed that any log entries on systems without known coords (via trilateration or EDDB) fail to display on the ED Toolbox log page.  The logs do start showing up after they get coords, whether they have a known (EDDB) system ID or not.

**Comment by DBnR1** [comment]
Ah, thanks for the report! I will fix it for the next beta release.

**Comment by DBnR1** [comment]
Fixed. You may replace the EDTB/get/getData.php from this repository with the one in your install to fix the issue or wait for the next official release.

EDTB/poi.php also had the same bug, and is also fixed.

**Comment by padthaitofuhot** [comment]
You rock, thanks!  I have some PR material I need to get into my fork as well that you might find interesting, such as pulling now playing data for Marvin from VLC's web interface.

**Comment by DBnR1** [comment]
Sounds interesting. The current now playing script of EDTB only works with text files and is not hooked up to Marvin. I'll keep an eye out for your script.

**Comment by padthaitofuhot** [comment]
Could log also show up based on last-known coordinates?  I'm getting a lot of logs that aren't displaying once I'm in unknown space.  Being as a fellow CMDR and I are circumnavigating the galactic ring at the moment, this tends to be an almost constant issue.  It's much easier to use the log to manually plot destinations and waypoints through unknown space when the entries I added 10ly ago still show up. :+1:

**Comment by DBnR1** [comment]
A good idea, I've implemented it and it will be available for the next release.
