### ISSUE TITLE
Feature request: Use EDSM trilateration targets

### ISSUE THREAD

**Issue by padthaitofuhot** [DBnR1/EDTB#2]
While EDTB's "RA GE KI WI" reference points are easy to use (and kind of funny if you've ever met my grumpy New Zealander buddy), they do not usually result in known-good location data on EDSM.  I'd love to see EDTB pull the desired trilateration distance queries from EDSM rather than using only using RA GE KI WI. Cheers.

**Comment by DBnR1** [comment]
I've recently changed the reference systems to Avik, Annarthia, Vorden and Wi for this very reason.
They provide better calculations than Rage Kiwi did, but not very reliable when calculating coordinates for systems far outside the bubble.

I've already decided to change the reference systems once more, and maybe something similar to what EDDiscovery does is possible in the future (deciding the reference systems based on the user's last know location)

Cheers!

**Comment by padthaitofuhot** [comment]
I like the new systems you're using.  However, main problem I keep running into is even after I provide the four distances to EDTB and submit them to EDSM, EDSM still wants more distances to update the coords on my public travel log.

**Comment by DBnR1** [comment]
Indeed that happens to me, too. At ~4 000 ly out it sometimes requires close to 10 reference distances before EDSM can get reliable coordinates. I assume it only gets worse the further away you are.

**Comment by padthaitofuhot** [comment]
When I'm that far out, I use EDSM's "Outlaying References" tab instead of "Standard References".  It makes a difference in the number of distances I need to submit for accurate matrices, but I still find I need six distances on average to get a high enough confidence for EDSM to believe it's found the coordinates.  

I was poking around their API docs looking for a way to pull reference candidates for a given system with unknown coordinates, but it doesn't support anything like that.  I'll talk to the dev and see if it's something they could put in their next API update.

**Comment by DBnR1** [comment]
Let me know if you get a response. Using reference systems based on the user's last known location makes perfect sense.

I'd probably still use the old ones because I'm lazy but it's nice to have options ;)

**Comment by DBnR1** [comment]
Trilateration reference systems in 1.1.0 are picked based on the user's last known location. Closing this.
