### ISSUE TITLE
Apache Server not starting (file not found)

### ISSUE THREAD

**Issue by Coruin** [DBnR1/EDTB#20]
After updating to 1.2.8 I receive the following error:

![error message](https://cloud.githubusercontent.com/assets/13752163/24878327/f9c633aa-1e32-11e7-9ddc-41f66a191e58.png)

As a result I'm no longer able to start the provided apache server.

I tried re-installing the current version with no success.

**Comment by Coruin** [comment]
Just figured out that disabling the anti virus/malware software during installation fixed the issue. Seems  like the software gets a (false) positive on the vbs file.

**Comment by DBnR1** [comment]
Thanks for reporting and debugging

**Comment by Coruin** [comment]
Just noticed that the anti virus/malware software also blocks the download of the update for systems and stations data. Appears very odd to me since I hadn't that issue before the latest edtb update
