### ISSUE TITLE
screenshot converter issue with file timestamps?

### ISSUE THREAD

**Issue by amatos** [DBnR1/EDTB#21]
Hello.

First, love the app.  I tried using the screenshot conversion function recently, and noticed some really strange behavior.  The .bmp files keep getting moved to the originals subdirectory, with a timestamp attached to the filename, but the converted jpgs never get created.

I believe that the problem is timezone related.  Specifically, in Makegallery.php, line 166:
$filetime = $filetime_o + ($system_time * 60 * 60);

This line is subtracting 4 hours (I'm in US Eastern DST, so GMT-4) from $filetime_o, so the check on line 171 ($filetime > $visit_time) always fails.  Changing line 166 to $filetime = $filetime_o corrects the problem for me.  I wanted to check about this logic prior to submitting a pull request to change it.

Regards,

Alberth

**Comment by DBnR1** [comment]
It does seem like line 166 is deliberately taking the timezone offset into account, but I can't remember the logic behind it :) There have been reports of the screenshot feature working intermittently at best, so maybe this is the reason. 

Please do submit a pull request and I'll check it out!
